name: Enterprise Devsecops CICD pipeline

on:
  push:
    branches:
      - qa
    paths:
      - client/**
      - server/**
      - .github/workflows/qa-ci.yml

env:
  ECR_REPOSITORY: nodejs-app
  AWS_REGION: us-east-1

jobs:
  docker:
    name: Docker build & push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag and push docker image to AWS ECR
        env:
         REGISTRY: ${{ steps.login-ecr.outputs.registry }}
         IMAGE_TAG: ${{ github.sha }}
        run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker tag $REGISTRY/$REPOSITORY:$IMAGE_TAG $REGISTRY/$ECR_REPOSITORY:latest
        docker push $REGISTRY/$ECR_REPOSITORY:lastest
